openrelik/openrelik-ui

- src/components/WorkflowTree.vue
- src/components/WorkflowTreeNode.vue
This PR aligns the "settings" icon vertically making the interface line up better.
> Workflow node style fixes

- src/views/File.vue
This PR adds Preview to HTML files in content view.
* Only (server side) allowed files with certain data_types will offer to preview in the UI
* Content is rendered in a sandboxed iframe (no scripts or external resources etc)
> Add preview for allowed HTML files

- src/components/TaskResultDefault.vue
- src/components/WorkflowTreeNode.vue
- src/layouts/default/AppBar.vue
- src/layouts/default/Default.vue
- src/layouts/default/View.vue
Improved the user interface to display file report summaries and runtime information more prominently within task results and workflow nodes.  Added a visual indicator for high-priority findings within file reports. Updated Vuetify toolbar component.
*   **Enhanced Task Result Display (TaskResultDefault.vue):**
*   Added a dedicated section to display file reports associated with a task, including a table showing the file name and a summary of the report. Files are linked to the file content view.
*   Report summaries for high-priority findings (priority < 21) are highlighted in red.
*   Capitalized the first letter of result keys for better readability.
*   Conditional rendering of result values to avoid displaying empty entries.
*   Improved styling and formatting for better visual …
> File Report UI

- src/components/WorkflowTaskDropdown.vue
- src/components/WorkflowTreeNode.vue
Improved the visual presentation and interaction with workflow nodes and files, adding tooltips for file names, truncating long file names, and styling the "Remove task" button.
* **File Name Tooltips:** Added tooltips to file names displayed under workflow nodes in `WorkflowTreeNode.vue`.  This addresses the issue of long file names obscuring other UI elements or being truncated without the ability to see the full name. The `:title="file.display_name"` attribute now provides a tooltip on hover, displaying the full file name.
* **File Name Truncation:** Implemented file name truncation for long file names within `WorkflowTreeNode.vue` using CSS classes `.file-container` and `.truncate`. This prevents excessively long file names from disrupting the layout while still providing a visual …
> Improve Workflow Node UI for Usability

- nginx/nginx.conf
- src/components/ProfileMenu.vue
- src/components/WorkflowTreeNode.vue
This PR enhances the Nginx configuration for improved performance and refines UI elements for better user experience in the Profile Menu and Workflow Tree Node components.
*   **Nginx Configuration Optimization:** The `nginx.conf` file has been modified to increase the `large_client_header_buffers` from `2 1k` to `4 32k`. This change allows Nginx to handle larger HTTP headers more efficiently, improving performance and reducing the risk of header-related errors, particularly with clients sending large cookies or complex headers. 
*   **Profile Menu Logout Method Change:** In the `ProfileMenu.vue` component, the logout method has been changed from an HTTP DELETE request to an HTTP POST request to `/logout`.
*   **Workflow Tree Node UI Refinements:** The `WorkflowTreeNode.vue` component has …
> Improve Nginx configuration and refine UI elements

- package.json
- src/RestApiClient.js
- src/components/UploadFile.vue
- src/views/Folder.vue
- yarn.lock
This change replaces the standard file upload functionality with chinked uploads using the `resumablejs` library.  This allows for more robust handling of large file uploads.
*   **Resumable.js Integration:** Added `resumablejs` library to handle chunked uploads. This library manages the process of splitting files into smaller chunks, sending them to the server, and reassembling them upon completion.
*   **Upload Component Refactoring:** The `UploadFile.vue` component has been significantly modified to integrate with `resumablejs`.  The single file input has been replaced with a multiple file input, and upload progress is now displayed per file.  The component now uses `resumablejs` to manage the upload process, including tracking progress and handling errors.  The logic for updating the …
> Chunked file uploads

- src/RestApiClient.js
- src/components/UploadFile.vue
- src/views/Folder.vue
- src/views/Home.vue
- src/views/Login.vue
Implemented redirect handling after login to preserve the original destination.
* **Preserved Redirect After Login:** The application now preserves the URL the user was attempting to access before being redirected to login. Upon successful login, the user is redirected to their original intended destination. This improves user experience by avoiding the need to navigate back to the desired page after logging in. This was implemented by adding redirect logic within `RestApiClient.js`, `Login.vue`, and `Home.vue`. Specifically:
*  `RestApiClient.js` now appends the current path to the `/login` redirect URL as a query parameter.
*  `Login.vue` stores this redirect URL in session storage.
*  `Home.vue` checks for this stored URL and redirects the user accordingly upon loading.
> Login Redirect Handling

- src/components/WorkflowTreeNode.vue
- src/views/File.vue
This PR enhances the user interface for displaying lengthy task configurations and adds more detail to the file view, including truncated lists of options, a "see more" toggle, and display of cloud storage details and source file links.
* **Truncated Task Configuration Display with "See More" Toggle:**  The workflow node display now truncates long lists of task configuration options to the first five items. A "See More/See Less" toggle has been added to allow users to expand and view the full list. This improves readability and reduces visual clutter for complex tasks.  This change was implemented in the `WorkflowTreeNode.vue` component by adding a `showOption` object to track the visibility state of each option list and conditionally rendering the list items based on this state.
* …
> Improve Task Configuration Display and File Details View

- package.json
- src/RestApiClient.js
- src/components/ProfileMenu.vue
- src/components/RangeChart.vue
- src/components/SystemMenu.vue
- src/components/TEMPLATE.vue
- src/components/ToggleTheme.vue
- src/layouts/default/AppBar.vue
- src/main.js
- src/router/index.js
- src/views/Metrics.vue
- yarn.lock
This PR introduces a new metrics dashboard to visualize task performance over time.  It includes new API endpoints, frontend components, and charting libraries to display various task-related metrics.
*   **New API Endpoint:** A new `/metrics/tasks` endpoint has been added to the `RestApiClient` to fetch task metrics data.  This endpoint accepts parameters for `metric_name`, `aggregate`, `range`, `step`, and `resolution` to customize the data retrieved.
*   **New Components:**
*   `RangeChart.vue`: This component is responsible for rendering the actual charts using the ApexCharts library. It takes props for chart configuration like the metric name, aggregation settings, and time window. The styling of these chart varies depending on the chosen theme (Dark/Light).
*   `SystemMenu.vue`: …
> Add Task Metrics Dashboard

- src/components/TaskStatusIcon.vue
- src/components/Workflow.vue
- src/components/WorkflowTree.vue
- src/components/WorkflowTreeNode.vue
- src/views/File.vue
- src/views/Folder.vue
Modified UI elements for better visual presentation, and reorganized workflow actions for clarity.
*   **Icon Change:** In `src/components/TaskStatusIcon.vue`, the success icon was changed from `mdi-check-circle-outline` to `mdi-check-circle` and the size is reduced to `small`. This provides a more compact and visually clear indication of success.
*   **Workflow Actions Consolidation:** Workflow actions such as "Copy", "Save as Template", and "Delete" have been moved from the `Workflow.vue` component to the `WorkflowTree.vue` component. This provides a more consistent location for these functions, in line with the visual presentation of the workflow itself.
*   **File and Folder View Improvements:** Both `File.vue` and `Folder.vue` were updated to include icons at the beginning of the …
> UI adjustments and workflow controls

- src/components/WorkflowTree.vue
- src/components/WorkflowTreeNode.vue
- src/styles/global.scss
- src/views/File.vue
Refactors the Workflow Tree component to improve visual clarity and consistency, and adds an "AI Summary" button.
*   **Component Restructuring:** The workflow action buttons (Run, Copy, Save as Template, Cancel) are now contained within a `div` element with a top border. This visually separates the buttons from the workflow tree, improving clarity. The action buttons are now padded on all sides.
*   **Theme Consistency:** Adds conditional classes for the action buttons, ensuring a consistent background color ("dark-grey-background" in dark mode, "white-background" in light mode) based on the current Vuetify theme.  The styles for these classes are now defined in `src/styles/global.scss` to make them globally available.
*   **Minor UI Tweaks:** Adds a "+" button to the workflow tree node …
> Improve Workflow Tree UI

- src/components/FileSummary.vue
Adjusted the visual style of the `FileSummary` component for better integration with the application's theme and added a subtle background gradient.
*   **Card Styling:** The `v-card` component's `variant` prop was changed from "outlined" to "flat" to remove the border. The toolbar color was set to transparent to make the card look like a part of the page.
*   **Toolbar Title:** The "Generated summary" text in the toolbar title was changed to "AI summary" to more accurately reflect the content.
*   **Background Gradient:** A CSS class `background-color` was added with a subtle linear gradient to improve the card's appearance and provide visual distinction.
> Improve File Summary Card

- src/RestApiClient.js
- src/components/FileSummary.vue
- src/styles/global.scss
- src/views/File.vue
Corrected minor UI theming inconsistencies and enforced consistent API endpoint naming.
*   **API Endpoint Consistency:** Removed trailing slashes from the `generateFileSummary` and `deleteUserApiKey` API calls in `src/RestApiClient.js`. This change aligns the API calls with a consistent style.
*   **UI Theming:** Replaced the inline style for the file summary card's background color with the `.ai-background-color` class from `src/components/FileSummary.vue`.  The style declaration was moved to `src/styles/global.scss`. This change promotes consistency in UI theming across the application.
*   **Theming Application:** Applied the `.ai-background-color` class to the "Generate AI Summary" button in `src/views/File.vue` to match the updated UI theme.
> UI Tweaks and API Endpoint Consistency

- src/RestApiClient.js
- src/components/FileSummary.vue
- src/layouts/default/AppBar.vue
Made minor UI adjustments for improved presentation and refined the API call for workflow execution.
*   **RestApiClient.js:** Removed `workflow_id` from the request body in the `runWorkflow` function. The API now only requires `workflow_spec`.
*   **FileSummary.vue:** Adjusted the layout of the AI summary component. The title is now rendered in a `div` element instead of a `v-toolbar-title`, allowing the "AI can make mistakes" disclaimer to appear on the same line. The goal is to reduce the vertical space occupied by this element.
*   **AppBar.vue:** Modified the logo rendering logic in the AppBar.  The logo source is now fixed to `/logo-light-round.png`. The size and margin are dynamically set based on the Vuetify theme (dark or light) to ensure appropriate presentation in both modes.
> UI Adjustments and API Refinement

- package.json
- yarn.lock
This release includes UI/UX improvements, API refinements, and dependency updates.  AI summary prompt display was added, and file summary cards were visually improved. Cloud disk functionality was removed.  Workflow tree UI and controls were also enhanced.  The file size limit for GenAI processing was adjusted.
* Added AI summary prompt display and improved visuals.
* Adjusted file summary card appearance and functionality.
* Removed cloud disk functionality.
* Improved workflow tree UI and controls.
* Updated various dependencies, including Vite.
* Adjusted file size limit for GenAI processing.
* Refined API endpoints for consistency.
> Version 0.5.0

- src/components/UploadFile.vue
- src/views/Folder.vue
Improves file upload error handling and simplifies LLM configuration loading.
*   **File Upload Error Handling:**
*   The `UploadFile.vue` component now emits a `file-upload-error` event when a file upload fails. This event includes the file object and the error message.
*   Added `maxChunkRetries`, `chunkRetryInterval` and `permanentErrors` options to `resumable.js` options.
*   The `Folder.vue` component listens for the `file-upload-error` event and displays an error snackbar to the user, providing more informative feedback about upload failures.  The dialog is closed when an error occurs.
*   **LLM Configuration Loading:** The `useAppStore` in `src/stores/app.js` has been refactored to simplify the logic for determining the LLM name. It directly uses the value from local storage, …
> Improved File Upload Handling and Configuration Loading

- src/RestApiClient.js
- src/components/FileSummary.vue
- src/components/FolderList.vue
- src/router/index.js
- src/stores/app.js
- src/views/File.vue
- src/views/Folder.vue
- src/views/Home.vue
Modified components for UI improvements, implemented folder search functionality, refined file access control, and adjusted the home page layout.
*   **API Addition:** Added `getAllFolders` to `src/RestApiClient.js`. This endpoint fetches all folders, optionally filtered by a search term.
*   **Component Styling Adjustments:** Modified `src/components/FileSummary.vue` to use `mb-4` class for spacing instead of `mt-4`. This change alters the vertical spacing of the component within its parent container for better visual flow.
*   **Folder List Updates:** Modified `src/components/FolderList.vue` to reduce default `items-per-page` to `10` and removed the cloud icons.
*   **Home Route Restructuring:** Changed the home route in `src/router/index.js` to render the `Home` component directly. …
> UI Improvements and Search feature

- src/components/WorkflowTaskDropdown.vue
- src/components/WorkflowTree.vue
- src/components/WorkflowTreeNode.vue
- src/views/File.vue
Updates the Workflow Task Dropdown and Tree components to improve usability and task management within the workflow editor.
*   **Workflow Task Dropdown Redesign:** Replaced the simple list in `WorkflowTaskDropdown.vue` with a `v-data-table` within a `v-menu`.  This allows for searching, and better organization of tasks via columns. The menu now closes only when explicitly requested.
*   **Search Functionality:** Introduced a search field in `WorkflowTaskDropdown.vue` to filter tasks by `display_name` and `description`.
*   **Workflow Tree Improvements:** Modified `WorkflowTree.vue` to disable the "run workflow" button when no tasks are available in the workflow specification. Styles are changed to flat buttons.
*   **Task Removal Enhancement:** Added a trashcan icon button to …
> New Task List dropdown

- src/RestApiClient.js
- src/components/FileChat.vue
- src/components/FileSummary.vue
- src/components/FolderList.vue
- src/components/TaskResultDefault.vue
- src/components/WorkflowTreeNode.vue
- src/views/File.vue
- src/views/Folder.vue
Introduces a File Chat component for AI-powered interaction with file content and refines the file content display, including layout and summary integration.
*   **File Chat Component:** Created a new `FileChat.vue` component that provides an interface for users to interact with a file's content using AI. This includes sending prompts, displaying chat history, and managing WebSocket connections for real-time communication.
*   **API Integration:** Added a `getFileChat` method to `RestApiClient.js` to retrieve chat history for a specific file, enabling the chat interface to display previous conversations.
*   **File View Modifications (`File.vue`):**
*   Refactored the `File.vue` component to include the `FileChat` component.  The component is displayed side-by-side with the file content …
> File Chat component and improved file content display

- .github/workflows/docker-image.yaml
Add github action to build container when
* a release is done
* a push to main is done (e.g. merge of PR)
> Add github action to build container

- src/RestApiClient.js
- src/components/SqlTables.vue
- src/views/File.vue
- src/views/Folder.vue
Adds functionality to query SQL database files directly within the application, and introduces a table schema viewer.
*   **API Integration:** Added `getSQLSchemas`, `runSQLQuery`, and `generateSQLQuery` methods to `RestApiClient.js`. These methods facilitate communication with the backend to fetch SQL schemas, execute SQL queries, and generate SQL queries from natural language input, respectively.
*   **SQL Tables Component:** Created a new `SqlTables.vue` component. It displays the schema of a SQL database in a tabular format, allowing users to browse tables and their columns.
*   **File View Modification:** The `File.vue` component is updated with a new tabbed interface for SQL files. This includes:
*   A SQL query editor with syntax highlighting and execution capabilities.
* …
> Add SQL support for file analysis

- src/layouts/default/AppBar.vue
- src/views/File.vue
Addresses issues with SQL query generation in the File View by cleaning up generated queries and adjusting spacing in the AppBar.
*   **SQL Query Cleanup:** In `src/views/File.vue`, the generated SQL query is now processed to remove code block markers (```) and newline characters. This change addresses a formatting issue where the raw SQL query returned from the backend was being displayed with unwanted characters in the UI. A comment has been added indicating that this cleanup is temporary and should be removed when the backend is fixed.
*   **AppBar Spacing Adjustment:** In `src/layouts/default/AppBar.vue`, spacing has been added around the `profile-menu` component by wrapping it in a `div` with `mr-2 ml-5` classes. This improves the visual layout and spacing of the menu items in the …
```
> Trim generated SQL query and switch place of AppBar controls
